### ISSUE TITLE
Rounded regular polygons

### ISSUE THREAD

**Issue by ay42** [spacenation/swiftui-shapes#1]

**Comment by ToddGeorgeKelly** [comment]
For my own purposes, I have altered the code to allow for rounded regular polygons based on a customizable 'radius' parameter. Would you like me to submit a pull request or are you wanting to do that part on your own?

**Comment by ay42** [comment]
@ToddGeorgeKelly please do. I'm curious to see how you have done it.

**Comment by ToddGeorgeKelly** [comment]
#10 is the pull request. As I have mentioned in my pull request, it IS missing functionality that would allow the inner lines of a '.strokeBorder()' polygon to be curved. I didn't need this for my project so I have't tried to address that issue, but I don't imagine it would be too crazy to add. 

Additionally, I only have about...4-5ish months of programming experience and am self taught, so I am not really in the know on all the 'best practices' out there. If I've done something glaringly awful, let me know, I love to learn.

Edit: Also, sorry for taking a week to post my pull request, I don't get on here often.
